name: Cleanup (safe)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      PR_PREFIX: cleanup/dupes-utf8

    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python and tools
        run: |
          set -euo pipefail
          sudo apt-get update -qq
          sudo apt-get install -y dos2unix >/dev/null
          python -m pip install --upgrade pip >/dev/null
          pip install chardet==5.1.0 >/dev/null

      - name: Dedupe and normalize (Python safe)
        run: |
          set -euo pipefail
          python3 - <<'PY'
import sys, hashlib, subprocess
from pathlib import Path
import chardet

ROOT = Path.cwd()

def fail(msg):
    print(f"::error::{msg}")
    sys.exit(1)

# получить список файлов
out = subprocess.run(["git","ls-files"], stdout=subprocess.PIPE, text=True, check=True)
files = [Path(p) for p in out.stdout.splitlines() if p and ".git" not in p]

# вычислить хэши
hash_map, dupes = {}, {}
for p in files:
    try:
        data = p.read_bytes()
    except Exception as e:
        fail(f"Cannot read {p}: {e}")
    h = hashlib.sha256(data).hexdigest()
    if h in hash_map:
        dupes.setdefault(h, []).append(p)
    else:
        hash_map[h] = p

deleted = 0
for h, group in dupes.items():
    keeper = hash_map[h]
    for p in group:
        try:
            p.unlink()
            print(f"Deleted duplicate: {p}")
            deleted += 1
        except Exception as e:
            fail(f"Cannot delete {p}: {e}")

converted = 0
for p in files:
    if not p.exists():
        continue
    if p.suffix.lower() in ('.md','.txt','.json','.csv','.py','.html','.xml','.yaml','.yml'):
        raw = p.read_bytes()
        if not raw:
            continue
        try:
            raw.decode('utf-8')
            continue
        except:
            pass
        enc = chardet.detect(raw).get('encoding') or 'utf-8'
        text = raw.decode(enc, errors='replace')
        p.write_text(text, encoding='utf-8')
        converted += 1

print(f"Duplicates removed: {deleted}, Files converted: {converted}")
PY

      - name: Commit and push safely
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          BRANCH="cleanup-utf8-$(date +%s)"
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "Cleanup: remove duplicates + normalize UTF-8"
          git push origin "$BRANCH" || (git fetch origin && git push origin "$BRANCH" -f)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.run_id }}
          title: "Cleanup: remove duplicates + normalize UTF-8"
          body: "Automated cleanup run — removed duplicate files and fixed encodings."
          base: main

          git commit -m "Clean duplicates and convert encodings to UTF-8" || echo "No changes to commit"
          git push
