name: Find Duplicate Files

on:
  workflow_dispatch:

jobs:
  find_duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Find duplicate filenames and print to log
        run: |
          echo "=== DUPLICATE FILES LIST ==="
          find . -type f | sort | uniq -d
          echo "=== END OF LIST ==="
